name: bodywashllm
channels:
  - defaults
  - conda-forge

dependencies:
  
  - python=3.10
  - pip

  
  - pandas=2.2.2
  - numpy=1.26.4
  - openpyxl=3.1.5
  - scikit-learn=1.5.1


  - tqdm=4.66.4
  - pyyaml=6.0.2
  - python-dotenv=1.0.1
  - requests=2.32.3

  - pip:
     
      - ollama  
